version: '3.8'

services:
  # Backend Service
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: backend
    ports:
      - "3000:3000"  # Expose backend port
    environment:
      - NODE_ENV=development
      - DATABASE_URI=mongodb://mongodb:27017/auth-app  # Connect to MongoDB by service name
      - JWT_SECRET=LJDt0djkSujtCBp
      - ALLOWED_ORIGIN=http://localhost:8080
      - PORT=3000
    volumes:
      - ./backend:/app
    networks:
      - mynetwork
    depends_on:
      - mongodb  # Ensure MongoDB starts before backend

  # Frontend Service
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: frontend
    ports:
      - "8080:8080"  # Expose frontend port
    environment:
      - NODE_ENV=development
    volumes:
      - ./frontend:/app
    networks:
      - mynetwork

  # MongoDB Service
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017"  # Expose MongoDB port
    volumes:
      - mongo_data:/data/db  # Persist MongoDB data
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge

volumes:
  mongo_data:
